version: '3.6'

services:
  express-dev:
    container_name: Express.js-DEVELOPMENT-container
    build:
      context: .
      target: DEV
    restart: always
    tty: true
    ports:
      - "3000:3000"
    volumes: # For debugging purposes
      - ./src:/code/src   
    environment:
      # DB credentials needed to connect to the db
      MONGODB_URI: ${MONGODB_URI}
      USER: 
      PASSWORD:
      PORT:
      NODE_ENV:
      DEBUG:

  express-prod:
    container_name: Express.js-PROD-container
    build:
      context: .
      target: PROD
    restart: always
    tty: true
    ports:
      - "3000:3000"
